// frontend/handson_f08/student-portal-vue/src/components/Header.vue
<template>
  <header class="header">
    <h1>Student Portal</h1>

    <p>
      Enrolled Courses:
      <strong>{{ store.enrolledCourses.length }}</strong>
    </p>
  </header>
</template>

<script setup>
import { useEnrollmentStore } from '../stores/enrollment'

const store = useEnrollmentStore()
</script>

<style scoped>
.header {
  background: #42b883;
  color: white;
  padding: 20px;
  text-align: center;
}

h1 {
  margin: 0;
}

p {
  margin-top: 10px;
}
</style>

// frontend/handson_f06/student-portal-routing/src/components/Header.jsx
import { Link } from "react-router-dom";
import { useSelector } from "react-redux";

function Header() {
  const enrolledCourses = useSelector(
    (state) => state.enrollment.enrolledCourses
  );

  return (
    <header>
      <h1>Student Portal</h1>

      <nav>
        <Link to="/">Home</Link> |{" "}
        <Link to="/courses">Courses</Link> |{" "}
        <Link to="/profile">Profile</Link>
      </nav>

      <h3>Enrolled Courses: {enrolledCourses.length}</h3>

      <hr />
    </header>
  );
}

export default Header;
